### PR TITLE
net: add back Buffers implementation

### LINKED ISSUE #4166: missing `net.Buffers`
Hi all!

I encountered the following error after upgrading tinygo from 0.29.0 to 0.31.0:
```bash
Error: ../../../../../../../go/pkg/mod/github.com/mailru/easyjson@v0.7.7/buffer/pool.go:171:14: undefined: net.Buffers
```
I did a little research and found out that `net.Buffers` was added in [this](https://github.com/tinygo-org/net/commit/c954718d79c8ad220f30fe5d2cc67fab185a2c66) commit but was later removed in [this](https://github.com/tinygo-org/net/commit/693edae782b7a2e82a7686dc7cd8bf37009bb8d9#diff-2fcb413ecd003cbcb8e5d2e08c7a80600a5b2da58869167c7dcb6f6f99752984L220) commit. Was there a reason for this?

The commit that removed net.Buffers contained the go1.19.3 source code, but [net.Buffers](https://cs.opensource.google/go/go/+/refs/tags/go1.19.3:src/net/net.go;l=712) is present.

### PR DESCRIPTION
**Pull request by deadprogram**
This PR is to add back the `Buffers` implementation originally added to the main repo in https://github.com/tinygo-org/net/commit/c954718d79c8ad220f30fe5d2cc67fab185a2c66 which got lost along the way to the switchover to this package.

Should fix https://github.com/tinygo-org/tinygo/issues/4166 and other similar issues.

### CODE REVIEW

**Comment by deadprogram** [comment]
Thanks for quick review @bgould :heart:
